use tempdir instead of working dir to extract archive

diff --git a/files/owncloud/upgrade-owncloud b/files/owncloud/upgrade-owncloud
--- a/files/owncloud/upgrade-owncloud
+++ b/files/owncloud/upgrade-owncloud
@@ -18,17 +18,22 @@ if ! tar tf "$ARCHIVE" owncloud/occ; then
 fi
 
 echo "Extracting $ARCHIVE ..."
-tar xf "$ARCHIVE" || exit 1
-if [ ! -d owncloud ]; then
+TEMPDIR=`mktemp -d`
+if [ ! -d "$TEMPDIR" ]; then
+	echo "tempdir creation failed"
+	exit 1
+fi
+tar xf "$ARCHIVE" -C "$TEMPDIR" || exit 1
+if [ ! -d "$TEMPDIR"/owncloud ]; then
 	echo "Something wrong. directory 'owncloud' not found in archive."
 	exit 1
 fi
 echo "Copying to DocumentRoot..."
-chown -R apache.apache owncloud
+chown -R apache.apache "$TEMPDIR"/owncloud
 echo "Stopping apache..."
 /etc/init.d/apache2 stop
-cp -a owncloud/. /var/www/localhost/htdocs/
-rm -rf owncloud
+cp -a "$TEMPDIR"/owncloud/. /var/www/localhost/htdocs/
+rm -rf "$TEMPDIR"
 echo "Executing upgrade script..."
 occ upgrade
 SERVER_NAME="localhost" php << EOF
