improved

diff --git a/resource/gpgpu/update b/resource/gpgpu/update
--- a/resource/gpgpu/update
+++ b/resource/gpgpu/update
@@ -1,11 +1,38 @@
 #!/bin/bash
-usage() {
-        echo "Usage: $0" 1>&2
-        exit 1
-}
+BOOTDIR=/.overlay/boot
 
-if [ "$#" -eq 0 ] ; then
-   usage
+# TODO: lock system
+
+mount -o remount,rw $BOOTDIR || exit
+
+rm -f $BOOTDIR/system.new $BOOTDIR/system.old
+
+AVAIL=$(df --output=avail $BOOTDIR | tail -1)
+IMGSIZE=$(stat -c %s $BOOTDIR/system.img)
+
+if [ -z "$AVAIL" -o -z "$IMGSIZE" ]; then
+  echo "Failed to get boot partition info."
+  exit 1
 fi
 
-echo "TBD"
+if [ $(($IMGSIZE / 1024)) -gt $(($AVAIL - 1024)) ]; then
+  echo "Insufficient available space on boot partition."
+  exit 1
+fi
+
+if wget -O $BOOTDIR/system.new http://dist.walbrix.net/gpgpu.img; then
+  if [ ! -f $BOOTDIR/system.cur ]; then
+    mv $BOOTDIR/system.img $BOOTDIR/system.cur
+  fi
+  mv $BOOTDIR/system.new $BOOTDIR/system.img
+else
+  echo "Download failed."
+fi
+
+if [ ! -f $BOOTDIR/system.img -a -f $BOOTDIR/system.cur ]; then
+  echo "Restoring system.img..."
+  mv $BOOTDIR/system.cur $BOOTDIR/system.img
+fi
+
+mount -o remount,ro $BOOTDIR
+echo "Done. Reboot system to take effects."
diff --git a/resource/walbrix/install b/resource/walbrix/install
--- a/resource/walbrix/install
+++ b/resource/walbrix/install
@@ -2,10 +2,12 @@
 SELF=$(findmnt -ln -o SOURCE /.overlay/boot)
 [ -b "$SELF" ] || SELF=$(findmnt -ln -o SOURCE /)
 if [ -b "$SELF" ]; then
+  SELF_MAJOR=$((16#$(stat -c %t $SELF)))
+  SELF_MINOR=$((16#$(stat -c %T $SELF)))
   SELF_PARENT=/dev/$(lsblk -n -o PKNAME $SELF)
   if [ -b "$SELF_PARENT" ]; then
-    SELF_MAJOR=$((16#$(stat -c %t $SELF_PARENT)))
-    SELF_MINOR=$((16#$(stat -c %T $SELF_PARENT)))
+    SELF_PARENT_MAJOR=$((16#$(stat -c %t $SELF_PARENT)))
+    SELF_PARENT_MINOR=$((16#$(stat -c %T $SELF_PARENT)))
   fi
 fi
 
@@ -27,7 +29,12 @@ if [ -z "$SECTOR_SIZE" -o -z "$NUM_512B_SECTORS" -o -z "$DEVICE_MAJOR" -o -z "$D
 	exit 1
 fi
 
-if [ $SELF_MAJOR -eq $DEVICE_MAJOR -a $SELF_MINOR -eq $DEVICE_MINOR ]; then
+if [ "$SELF_MAJOR" -eq "$DEVICE_MAJOR" -a "$SELF_MINOR" -eq "$DEVICE_MINOR" ]; then
+  echo "You can't install system on currently running device".
+  exit 1
+fi
+
+if [ "$SELF_PARENT_MAJOR" -eq "$DEVICE_MAJOR" -a "$SELF_PARENT_MINOR" -eq "$DEVICE_MINOR" ]; then
   echo "You can't install system on currently running device".
   exit 1
 fi
@@ -43,9 +50,12 @@ if [ $NUM_512B_SECTORS -lt 15000000 ]; then
   PARTITION_SIZE=-1
 fi
 
-parted --script "$DEVICE" mklabel "$PARTITION_TABLE_TYPE"
-parted --script "$DEVICE" mkpart primary 1MiB "$PARTITION_SIZE"
-parted --script "$DEVICE" set 1 boot on
+parted --script "$DEVICE" "mklabel $PARTITION_TABLE_TYPE"
+parted --script "$DEVICE" "mkpart primary 1MiB $PARTITION_SIZE"
+if [ "$PARTITION_SIZE" != "-1" ]; then
+    parted --script "$DEVICE" "mkpart primary $PARTITION_SIZE -1"
+fi
+parted --script "$DEVICE" "set 1 boot on"
 if [ "$PARTITION_TABLE_TYPE" == "msdos" ]; then
   parted --script "$DEVICE" set 1 esp on
 fi
@@ -118,7 +128,7 @@ echo "Installing System image..."
 
 cp $SYSTEM_IMAGE $TMPDIR/system.img
 
-echo "Syncinc..."
+echo "Syncing..."
 
 umount $TMPDIR
 rmdir $TMPDIR
